=== Initial effects of God's Word

==== Introduction
* Practical effects of God's Word on those who receive it

> 12 For the word of God is living and active, and sharper than any two-edged sword, piercing even to the dividing of soul and spirit, of both joints and marrow, and is able to discern the thoughts and intentions of the heart.
> -- Hebrews 4:12 WEB

* Active / powerful is the Greek word for "energetic" (intense, vibrant...)

> 63 It is the spirit who gives life. The flesh profits nothing. The words that I speak to you are spirit, and are life.
> -- John 6:63 WEB

* His Words are spirit and life!

> 13 For this cause we also thank God without ceasing that when you received from us the word of the message of God, you accepted it not as the word of men, but as it is in truth, God’s word, which also (effectively) works in you who believe. 
> -- 1 Thess. 2:13 WEB

* God's Word's are not just pen strokes or sounds, but it is alive and energetically active, accomplishing His will in conjunction with the Spirit, in thos who believe it and receive it

==== Response Determines Effect
* The Bible shows us that the effectiveness of God's Word is based on how people respond to it

> 21 Therefore, putting away all filthiness and overflowing of wickedness, receive with humility the implanted word, which is able to save your souls.
> -- James 1:21 WEB

* Filthiness - perverse delight in licentiousness and impurity
* Naughtiness - refusing to accept instruction or correction (like child)
** Often attitude of unrenewed soul towards Elohim

> But indeed, O man, who are you to reply against God? Will the thing formed ask him who formed it, “Why did you make me like this?”
> -- Romans 9:20 WEB

> 2 “Shall he who argues contend with the Almighty? He who argues with God, let him answer it.”
> -- Job 40:2 WEB

* Naughty Attitude
** Both close heart and mind to the beneficial effects of God's Word.
* Meekness (opposite attitude) - Fear of the Lord (reverance and respect)
** Associated ideas: Humility, Sincerity, Patience, Openess (Mind & Heart), Quietness

> 8 Good and upright is Yahweh, therefore he will instruct sinners in the way.
> 9 He will guide the humble in justice. He will teach the humble his way.
> 12 What man is he who fears Yahweh? He shall instruct him in the way that he shall choose.
> 14 The friendship (secret) of Yahweh is with those who fear him. He will show them his covenant.
> -- Psalm 25:8-9,12,14 WEB

* Description of Man able to receive instruction & blessing from the Lord
* In summary Word is active and has different effect on people based on how it is received


> 18 For the word of the cross is foolishness to those who are dying, but to us who are being saved it is the power of God.
> -- 1 Coritnhians 1:18 WEB
* Like the Gospel which also divides based on how people respond
* Word is sharp (Heb. 4:12) in that it also divides people into two classes (rejecters & receivers)
** Discerns the thoughts and intents of the heart

> 34  “Don’t think that I came to send peace on the earth. I didn’t come to send peace, but a sword.
> 35  For I came to set a man at odds against his father, and a daughter against her mother, and a daughter-in-law against her mother-in-law.
> -- Matthew 10:34-35 WEB

* Jesus did not come to bring peace, but a sword..
** Will sever the closest of earthly bonds

==== Faith
* For those who reeive the word with openenss, meekness etc.
** i.e. the right attitude
* Study the various effects it has on people
* Look at it in order, by starting with faith

> 17 So faith comes by hearing, and hearing by the word of God.
> -- Romans 10:17 WEB

* Faith is produced
* This spiritual process has 3 phases
** Logos (The Word) is needed
** Hear - Logos needs to be heard with focused attention / aroused interest
** Faith - The product of hearing
* Without real interest described by hearing, faith will not be produced
* Hearing starts a process in your inner being that takes time to develop
** Why so many christians lack real faith - don't devote time to hearing
*** If time dedicated to the study of the Word it is done haphazardly and hurriedly
*** All over before faith has had time to develop
* Scriptural faith is defined as...
** Believing that what God has said in His Word will come to pass or He will do!
** It's not about believing something you want to happen...

> 23 Now, Yahweh, let the word that you have spoken concerning your servant, and concerning his house, be established forever, and do as you have spoken.
> -- 1 Chronicles 17:23 WEB

* Scriptural faith = "Do as you have spoken..."

> 38 Mary said, “Behold, the servant of the Lord; let it be done to me according to your word.”
> -- Luke 1:38 WEB

* Mary exercised Scriptural faith

> 6 Without faith it is impossible to be well pleasing to him, for he who comes to God must believe that he exists, and that he is a rewarder of those who seek him.
> -- Hebrews 11:6 WEB

* The first effect of God's word is faith
* This is necessary as this kind of faith is fundamental to and good / positive interaction with the Lord
** An interaction, with a person,that pleases Him
* Faith is the first and most important response in your interaction with Elohim
** If you come to God you must believe (Heb.11:6)!

==== The New Birth
* After faith, God's Word produces the following effect in our lives: the New Birth

> 18 Of his own will he brought us forth by the word of truth, that we should be a kind of first fruits of his creatures.
> -- James 1:18 WEB

* A christian who is born again obtains a new life that is birthed by the Word of God that he receives by faith

> 23 Having been born again, not of corruptible seed, but of incorruptible, through the word of God, which lives and remains forever.
> -- 1 Peter 1:23 WEB

* Scripture & Nature agree in that a seed will produce after its kind
** An incorruptible seed will produce that which is incorruptible
* So it is with the new birth
* Seed is divine
* Life of God Himself

> 9 Whoever is born of God doesn’t commit sin, because his seed remains in him; and he can’t sin, because he is born of God.
> -- 1 John 3:9 WEB

* Your new nature by identity is not sinful as it is born of the incorruptible seed of God's Word
** Pure & Holy Nature
* Doesn't mean a born again christian cannot sin
* Means he can choose not to sin
* He is enabled and empowered to overcome sin
* Unregenerate man cannot
* In every Christian there is a war between the...
** new man - holy & righteous
** old man - depraved, corrupt

> 22 that you put away, as concerning your former way of life, the old man that grows corrupt after the lusts of deceit,
> 23 and that you be renewed in the spirit of your mind,
> 24 and put on the new man, who in the likeness of God has been created in righteousness and holiness of truth.
> -- Ephesians 4:22-24 WEB

* As long as the old man is kept under subjection, the new man can exert its proper control
** Fruit will be victory & peace in contrast to the enslavement that comes by giving the "old man" control

==== Spiritual Nourishment
* Every new born creature needs nourishment as soon as its born
** Stay alive and to grow
* It is the same with the spiritual man
* Spiritual life needs the Word of God as nourishment for each phase

> 1 Putting away therefore all wickedness, all deceit, hypocrisies, envies, and all evil speaking,
> 2 as newborn babies, long for the pure milk of the Word, that you may grow thereby."
> -- 1 Peter 2:1-2 WEB

* New born babes - pure milk of the Word
** Note milk can become rancid if it comes into contact with unclean
** Same with those who are born again - hearts need to be cleansed in order for Word-milk to be effective
*** Get rid of wickedness, evil ...

> 4 But he answered, “It is written, ‘Man shall not live by bread alone, but by every word that proceeds out of God’s mouth.’”
> -- Matthew 4:4 WEB

* As you grow the Word also offers more substantial meat e.g. alikened to Bread (Matthew 4:4)
** Need to go beyond just your daily verse and Study the whole Bible
* George Mueller was in large part successful not just because of his faith and prayer life, but also He read the Bible through several times a year

> 12 For when by reason of the time you ought to be teachers, you again need to have someone teach you the rudiments of the first principles of the oracles of God. You have come to need milk, and not solid food.
> 13 For everyone who lives on milk is not experienced in the word of righteousness, for he is a baby.
> 14 But solid food is for those who are full grown, who by reason of use have their senses exercised to discern good and evil.
> -- Hebrews 5:12-14 WEB

* Writer of Hebrews rebukes the Hebrew believers as they had beleived many years, but had not studied and applied the Word
** Thus stayed infants
* Writer of Hebrews assures us that the regular systematic study of the scriptures will develop and mature us
