== THE KINGDOM is my Politics!

=== Kingdom Manifesto
* We believe that Jesus is the only, ultimate King.
* Unless a political system fully and wholly acknowledges this truth it is doomed to fail!
* We must therefore as a Nation fully acknowledge him first and foremost as the ultimate sovereign of *COUNTRY_NAME*.
* He asked before he left earth that we are to make disciples of all Nations.
* He also said that He would return one day to finally bring everything under His authority.
** Accordingly the goal of this political party will be to put laws and education in place that are based on His commandments as set out in the Bible
* Though we will not force people to become followers of Christ
** We will put laws in place and teach people to follow his ways as this is the only path for a Nation that will ultimately succeed.
** Because when He returns this will happen anyway.
** And we know since He created the universe and He is the ultimate King of all, those who follow his ways will be blessed.
** Accordingly, a Nation that follows His ways will be blessed and need not fear His judgement when He returns.
* Though we would like to perfectly do the above and create Heaven on Earth, we know this is a difficult goal, but we would like to begin moving in this direction and rest on His grace to help us.