== Hebrew & Greek Thinking

=== When I was younger...
* Someone gave me a prophetic word
* That the Lord would bring together head and heart in and through my life
* I have difficulty finding people who can do this well...
* My life has been a pendulum swinging between these 2 so called extremes
* I find it interesting that Hebrew and Greek thinking represent these 2 aspects well

== Questions
* Do we need greek philosophy and hebrew philosophy as rep. in the Bible to be whole?
* Could we simply live just with Ruach and Logos working together?
* Or do the Greeks help us to formulate the questions we have answered in Jesus and that His Spirt & Word can teach us?
* How do we formulate Jesus as the answer to the questions of this world increasingly shaped by greek thinking...?

=== Conclusions
* Hebrew thinking
** focuses on right action and right emotions / feelings (heart and body)
** More practical and relationally focused
* Greek thinking
** focuses on thinking right (mind)
** Abstracts
** Correctness
** Knowledge
* Both together with the guidance of the Trinity lead to wholeness in humanity
* HOWEVER, if we only develop in one type of thinking...
** We can become lopsided!
** We can cut ourselves off from faith-filled living that leads to action (only greek logic)
** We can become esoteric (gnosticism) and live in a worlf of fantasy that may be interesting, but lead to muddled thinking
* Only through Yeshua can we enter into true wholeness
** He leads the way and empowers us into right thinking, feeling and action through Ruach working with Yeshua (Rhema & Logos & Logos Sarx Gegonen)

=== References
* https://www.memoriapress.com/articles/hebrew-better-greek/
* https://www.ancient-hebrew.org/language/philosophy-of-the-hebrew-language.htm
