== The Bible

=== Introduction

* Over 1 billion people worldwide identify themselves with the Christian Faith.
* Most agree that the Bible is the authoritative basis of their faith and how they practice it
* The Bible is considered important in 2 other major world religions: Judaism & Islam
* It is the most read and influential book
* Anyone seeking a good general education cannot ignore reading the Bible

=== Influence

* It is considered by people from different cultures, ages, classes etc. as the basis of their faith
* Has profoundly influenced Western Culture and most world cultures have been influenced by it in some way or another
* It is made up of two major sections

=== Structure

The Bible is made up of 2 sections: The Old and New Testament.
In total, it is comprised of 66 Books of various lengths.

=== Old Testament (Tanakh)

* 39 books
* Primarily written in Hebrew (some parts in Aramaic)
* Main flow of the OT "Story"
** Creation, Adam & Eve, Fall of Man, Promise to restore
** Abraham and start of Nation of Israel
** Promise that Elohim will redeem mankind through the Abrahamic lineage
** Describes Elohim's dealings with the nation of Israel over roughly 2000 years and how he is preparing the world for the coming messiah who will redeem mankind
*** Individuals & Nation
*** Judgements & Justice
*** Wisdom & Power
*** Mercy & Faithfulness
*** Faithfulness to keep His covenants even though mankind breaks them
*** Promise, sealed with a covenant, to send a deliverer who would redeem mankind and restore us back into relationship with Elohim

=== New Testament (NT)

* 27 books
* Primarily written in Greek
* Some newer manuscripts have also been found in Aramaic
* Main flow of the NT "Story"
** Describes the coming of Elohim’s solution to man’s ultimate problem in the person of Jesus Christ, the Messiah
** Messiah / Christ - The Anointed One
** Fulfils everything promised in the Old Testament
** Thus the new and the old form a unity
** Describes the lives of the first people who were redeemed
** Ends with a prophetic picture of the end this age and the beginning of a wonderful eternity where the redeemed as Christ’s Bride live in perfect harmony with Elohim…
