=== The Foundation of the Christian Faith (Jesus Christ)

==== Introduction
* Believer’s life the construction of a Building
* Examples:

> 20 But you, beloved, keep building up yourselves on your most holy faith, praying in the Holy Spirit.
> -- Jude vs. 20 WEB

> 9 For we are God’s fellow workers. You are God’s farming, God’s building.
> 10 According to the grace of God which was given to me, as a wise master builder I laid a foundation, and another builds on it. But let each man be careful how he builds on it.
> -- 1 Corinthians 3:9-10 WEB

> 22 in whom you also are built together for a habitation of God in the Spirit.
> -- Ephesians 2:22

> 32 Now, brothers, I entrust you to God and to the word of his grace, which is able to build up, and to give you the inheritance among all those who are sanctified.
> -- Acts 20:32

* Natural Order - You first need to lay a foundation before you can build
** Spiritual order is similar
* You can only support a small building on a weak foundation
** Similarly, a strong foundation can support larger buildings
* Many christians struggle with the following:
** Start off with grand plans,
*** but because they do not build a strong foundation,
*** their building ends up in a heap of ruins (unanswered, prayers, vows and intentions unfulfilled…)
*** The real problem lies beneath the ruins
**** A poor foundation was laid
* My Testimony
** I have been following Jesus for many years now, but I must admit when I look back I did not build a strong foundation
** I spent a lot of time doing things for Elohim, and I built my life in a very haphazard, sporadic, Bedouin way
** I was very unstable accordingly and my life was filled with doubt
** I should have spent more time building a strong foundation
*** instead of trying to always be the big spiritual leader...
**** present at every event,
**** always looking to pioneer something new etc.

==== Christ the Rock
* Accordingly, we should ask ourselves the following question…
** What is Elohim’s appointed foundation on which we should build our christian life?
* Jesus Christ is the foundation!

> 11 For no one can lay any other foundation than that which has been laid, which is Jesus Christ.
> -- 1 Corinthians 3:11

> 6 Because it is contained in Scripture,
> “Behold,[a] I lay in Zion a chief cornerstone, chosen and precious: He who believes in him will not be disappointed.”
> -- 1 Peter 2:6

> 16 Therefore the Lord Yahweh says, “Behold, I lay in Zion for a foundation a stone,
> a tried stone, a precious cornerstone of a sure foundation. He who believes shall not act hastily.
> -- Isaiah 28:16 (showing the Old & New Testament agree in this fact)

* Nothing else can be the foundation!
** Creeds
** Denominations
** Traditions
** Church
** Ordinance
** Ceremony

> 13 Now when Jesus came into the parts of Caesarea Philippi, he asked his disciples, saying, “Who do men say that I, the Son of Man, am?”
> 14 They said, “Some say John the Baptizer, some, Elijah, and others, Jeremiah or one of the prophets.”
> 15 He said to them, “But who do you say that I am?”
> 16 Simon Peter answered, “You are the Christ, the Son of the living God.”
> 17 Jesus answered him, “Blessed are you, Simon Bar Jonah, for flesh and blood has not revealed this to you, but my Father who is in heaven. 18 I also tell you that you are Peter,[a] and on this rock [b] I will build my assembly, and the gates of Hades[c] will not prevail against it.
> -- Matthew 16:13-18

** Some mistakenly believe Jesus is saying He will build his Church upon Peter
*** This is nonsense!
*** Petros - small rock
*** Peter was just a man with many failings even though a charismatic, born leader
**** Matthew 16:22-23 - Get behind me satan
**** Denied the Lord 3 times
**** Galatians 2:11-14 - Separated himself because of the fear of the Judaizers
*** Rather consider…
**** Psalm 18:2 - The Lord is my rock
**** Psalm 62 - He only is my rock and my salvation
***** Rock - 3 times
***** Salvation - 4 times
**** ONLY - Only the Lord!

> 12 There is salvation in no one else, for there is no other name under heaven that is given among men, by which we must be saved!”
> Acts 4:12
**** Peter himself says,”Nor is there salvation in any other…”

==== Confrontation
* How do we build on Jesus the rock?
* 4 Stages seen in Matthew 16:16
** Confrontation
*** You need a definite, personal experience with Jesus
*** No mediator or any other human being playing a go between
*** No basing your faith on someone’s nice ideas, emotions etc.
*** Testimony
**** When I was 7 years old I attended a School for children at a Rhema conference where they told me about Jesus and what he had done for me. This was not the first time I had heard about Jesus, but this time I really felt I needed to respond to the message. I remember, later at home, holding this pamphlet in my hands with a picture of Jesus on the cross and appreciating what Jesus had done for me as well as being in a repentant state
**** I also remember a dream one night where Jesus came on a chariot to fetch people and he spoke to me and said one day He would come and fetch me, but in the meantime I was to commit myself to His Word!

==== Revelation
> 13 However when he, the Spirit of truth, has come, he will guide you into all truth, for he will not speak from himself;
>    but whatever he hears, he will speak. He will declare to you things that are coming.
> 14 He will glorify me, for he will take from what is mine, and will declare it to you.
> -- John 16:13-14 WEB

==== Acknowledgement
> 3 This is eternal life, that they should know you, the only true God, and him whom you sent, Jesus Christ.
> -- John 17:3

> 13 These things I have written to you who believe in the name of the Son of God, that you may know that you have eternal life, and that you may continue to believe in the name of the Son of God.
> 20 We know that the Son of God has come, and has given us an understanding, that we know him who is true, and we are in him who is true, in his Son Jesus Christ. This is the true God and eternal life.
> -- 1 John 5:13,20

> 12 For this cause I also suffer these things.
> Yet I am not ashamed, for I know him whom I have believed, and I am persuaded
> that he is able to guard that which I have committed to him against that day.
> -- 2 Timothy 1:12

==== Confession
* Are you a christian?
** Many say, "I hope so..."
** Very wishy-washy
* If you have built on an encounter with Jesus your answer should be "Yes & Amen!"

> “Acquaint yourself with him, now, and be at peace.
> By it, good will come to you.
> -- Job 22:21

==== References
* Foundational Truths for Christian Living (Derek Prince)
* https://www.youtube.com/watch?v=ZMJ2gH7-izI&list=PL_L1za0tEXFV0IcU_dXAX2Kk2YePSzQJv[Build the Foundations of Your Faith - Laying The Foundation, Part 1, Founded on the Rock]
