=== The Authority of God's Word
* The Word's Authority

==== TODO
* https://www.ancient-hebrew.org/studies-words/what-is-torah.htm

==== Introduction
> 34 Jesus answered them, “Isn’t it written in your law, ‘I said, you are gods’?
>
> 35  If he called them gods, to whom the word of God came (and the Scripture can’t be broken),
>
> 36  do you say of him whom the Father sanctified and sent into the world, ‘You blaspheme,’ because I said, ‘I am the Son of God’?
> -- John 10:34-36 WEB

* 2 titles used for the Bible
** The Word of God
*** Jesus was saying the truths revealed are not from man, but from God
*** Men are only channels
** The second: Scripture - explained below
*** That which is written

==== The Bible - God's written Word
* The scripture
** Reveals its constraints (Divinely appointed limitation of the Bible)
** Means: "That which is written"
** Does not contain the entirety of all of His thoughts, of what God has said and done, His purposes etc.
*** That is it doe not contain every detail
** Also doesn't contain all the divinely inspired messages given through humans
*** Not all utterances of the prophets mentioned were recorded in the Bible
*** Bible states this (John... if all that Jesus did was recorded...)
* Though the Bible is completely true and authoritative, it is highly selective!
* Message primarily for the human race
** Expressed in words we can understand
** Centrla theme is man's wellbeing
** Shows how man has sinned and fallen and can be restored through the faith in the finished work of Jesus
* Jesus sets approval upon the Bible's claims for supreme and divine authority
** "Scripture cannot be broken"
* Men were only channels when they wrote these books
** These days we are able to control satelllites millions of miles away with radio waves we cannot see
*** Only people with the most unscientific minds would reject the idea God could not do this with His creation

==== Inspired by the Holy Spirit
* The Bible clearly describes how God directed and communciated with the people who wrote the scriptures
** Through the Holy Spirit

> 16 Every Scripture is God-breathed and profitable for teaching, for reproof, for correction, and for instruction in righteousness,
>
> 17 that each person who belongs to God may be complete, thoroughly equipped for every good work.
> -- 2 Timothy 3:16-17 WEB

* By inspiration - means literally "inbreathed of God" - connected with word Spirit

> 19 We have the more sure word of prophecy; and you do well that you heed it as to a lamp shining in a dark place, until the day dawns and the morning star arises in your hearts,  
>
> 20 knowing this first, that no prophecy of Scripture is of private interpretation.
>
> 21 For no prophecy ever came by the will of man, but holy men of God spoke, being moved by the Holy Spirit.
> -- 2 Peter 1:20-21

* "Moved by" - "Borne along by / Directed in their course by"

> 6 Yahweh’s words are flawless words, as silver refined in a clay furnace, purified seven times.
> -- Psalm 12:6
* Furnace - human vessel
* Silver tried 7 times - absolute perfection of the Holy Spirit's Work

==== Eternal, Authoritative
* Psalm 119:89 - Forever, Word, Settled in Heaven
** Bible is the product of eternity and not time
** Bible contains the eternal counsel and mind of God
* Matthew 24:35 - My words will not pass away
* Psalm 119: 160 - entirety of your Word is truth
** Jesus, Disciples and all Jews of the time accepted entirety of OT scripture as authoritative
* Matthew 4:1-10 - Jesus quoted scripture to defeat the enemy (It is written...)
* Matthew 5:17-18
** Jot - smallest letter in the Hebrew Alphabet
** Tittle - small curve added to the ends of letters
** Jesus saying not one bit of His Word will be corrupted or pass away (be of no use)
* Jesus often quoted the Scriptures as a basis for His point of view
** Matthew 19:4 - At the beginning reference to Genesis
** Matthew 22:32 (Exodus 3:6 - Jesus saying still valid today)
*** Have you not read what was spoken to you by God?
* Entire life of Jesus was directed in every aspect by the Scriptures
* If the OT scriptures are not absoloutely accurate or authoritative then Jesus was a lier or deluded

====  Coherent, Complete, All Sufficent
* New Testament Authority
* Matthew 28:19-20 - Make disciples...teaching them to obey what I have commanded...
* Matthew 23:34 - I send you... scribes (Jesus intended for his teachings to be set down in writing)
* John 14:26 - Jesus made provision for complete accuracy through his Holy Spirit of what was said (past)
* John 16:13-15 - And for the impartation of new truths through the Holy Spirit
* 2 Timothy 3:16 - All Scripture! (OT & NT) can be used for teaaching...
* 2 Peter 3:1-2 - Be mindful of the words spoken by the prophets and of the commandment of us the apostles
** Peter sets OT prophets and commands of apostles on the same level
* 2 Peter 3:15-16 - rest of scriptures (Sets Pauls writing on the same level)
* Paul only knew Jesus through divine revelation from the Holy Spirit. Did not know him in his earthly ministry
* Luke 1.3 - same with Luke who had perfect understanding of all things from the "very first" (from above)
* John 3:3 - Being "born again" (from above) refers to the Supernatural Intervention of the Holy Spirit
* So we see that the OT & NT are authoritative, Spirit breathed words of God that are still accurate
** Complete and sufficeint revelation of God
* Nothing is inconsistent with logic, science or common sense
** In fact, much in all 3 required to confirm this.
