== Unpunishable: Introduction

The completely different way in which the New Covenant challenges us to respond to people's mistakes.
Apart from sin entering the World after the Fall of mankind, what also happened is that "the punishment paradigm" entered with it.

And as mankind became spiritual orphans seperated from God and no longer being a part of His family,
we had no way of fixing the situation through our own strength and were condemned to live in fear of the punishment of God whilst seeking to:

* Make things right by keeping the rules
* Run away from God and rebelling
** Thinking or saying that God is evil and unjust
** In rage, sticking up our finger at God and telling Him that we don't care about the consequences
*** Then choosing to live for the moment and do what we deem is best
* Finding so called clever scientific reasons for "Who God doesn't exist!"
* Trying to change the rules thinking if we set them then we can be in control
* ... the list goes on...

All of this in the name of self preservation, but deep down actually being driven by fear!

But God in His Mercy sent his son Jesus to free us from sin, satan and death!
He made a way for us to be restored in our relationship with God without us trying to follow a set of
laws perfectly that we aren't able to follow anyway.

Jesus came to make us orphans into sons and daughters again,
transforming us form the inside out so that we could become driven by love
as we endeavour to build connection with the Trinity, ourselves and the world.





