=== Steward

==== Introduction
* I had a revelation about this when I was struggling with a problem that had been plaguing me more than 20 years
* I had this weird war going on inside of me when it came to purchasing stuff, particularly clothes
* Initially, I had this deep desire / compulsion to buy things
* Some of the things that I would say would be...
** I need this now in order to solve this problem
** If I don't buy this it won't be available in a few months
** Just in case (the world economy implodes...), I need to buy more than I need
* Initially, I would give away, burn, or throw out the things I felt I should not have bought
* After many years it got to the point I would have such fear come on me when I bought things
* Elohim was good to me when I was in a time of prayer (2023-07-14)
* I had chosen to come back to the tent and I went into the Holy of Holy's
* Before I entered I washed myself with His blood and my hadns with water
* When I was in the Holy of Holy's
* The Lord reminded me how the articles of the tent were consecrated
* I felt I needed to prophetically consecrate these shirts with Yeshua's blood (Exodus 29)
* By touching them in faith as those I was putting a drop of blood on them
* I also felt His presence was consecrating these items
* I felt He was saying to me, consecrate and give to him everything I bought
* I should see nothing as something I own on my own
* Instead, see everything in my care as a son who is stewarding what beloings to His Father

==== Look at the Word

===== Genesis 1:28 - Called to Steward by Ruling
> 26 God said, “Let’s make man in our image, after our likeness. Let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth.”
>
> 27 God created man in his own image. In God’s image he created him; male and female he created them.
>
> 28 God blessed them. God said to them, “Be fruitful, multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth.”
> -- Genesis 1:26-28 WEB

* The word "dominion" in hebrew is
** וְיִרְדּוּ / wê'yir'du
*** RULE(V): (רדה / r.d.h) To exert control, direction, or influence over, especially by curbing or restraining; to spread out through a land through authority or by walking among the subjects. Strong's: #7287

===== Malachi 3:10

===== Luke 12:42

===== 1 Corinthians 4:2

===== 1 Peter 4:10

===== Colossians 3:23

==== Practical Application
* When I am about to
** Purchase something
** Do something
* Invest in something
* Ask yourself
** Am I stewarding the time, resources etc. that YHWH has given me?
** Will I be able to steward what I am about to purchase / receive well?
