=== Husbands & Wives

==== A powerful conversation...
My wife had had some time off for a wellness weekend and we sat down to reconnect,
enjoying the late summer sun (2023-09-03).
We were just starting out in a small group that had as focus "marriage" for the next year,
and we had an assignment to talk about our vision.
But there was a bit of an elephant standing in the room (even though we were outside).
Our leaders had a strong conviction around the importance that husbands and wives were to live becoming a single entity, and seeing each other eye to eye.

Though in principle I agreed we needed to become one and that both parties needed to respect each other which is something that has not been lived in most marriages, I couldn't simply ignore the scriptures calling me to ultimately be the head of the family.
I said to my wife that I had no need to control her and that I wanted to create a space for respect and space for each of us to be fully ourselves.
It was just that when I was young I had had a dream that Jesus had spoken to me and asked me to know His Word, meaning also I needed to carefully guard what was said in it and to obey it, internalize and live it out as well as spread it!
Having had some time to reflect, my wife said to me the real issue is that she wanted to make sure that she would be heard and respected.

This was the key point.

Some back story is that my wife had constantly to deal with friends and customers in our neghbourhood that were in male dominated marriages,
where they were the one's who had to simply listen to what their husbands commanded.
Every time she felt slightly cut off or unappreciated this would haunt her that our relationship would head in this direction.
Though I asked her whether this was the way I treated her, it was in many ways an ungrounded fear,
nevertheless, I said to her that I wanted to lead like Jesus as a servale leader.
At any moment she could challenge me if she felt this was not the case in a situation where I was cutting her off and telling her to just listen to me
whithout giving her a chance to share her thoughts.

I made a decison at this moment to carefully consider how I was treating and communicatinig with my wife.
My goal was to love and respect her in such a way that I wouldn't need to ask her to respect me as the head of the family,
but that she would do so from her own conviction and decison to do so with a happy heart as she knows she is loved and respected
and we are one, on the same team.

==== Key Points
* We are both made in the image of God
* A husband and his wife are a perfect, complete image of God
** The image we represent is that of Christ and his Ecclesia

==== Vision
* Though a man is the head and carries the responsibility of setting the direction of the marriage and the family
* It is important that models his leadership on Christ who calls his bride to come up to him and co-reign with him (<<ephesians-2-vs-4-6>>).


==== Appendix A: Scriptures

===== Genesis 1 vs 26-30

> 26 God said, “Let’s make man in our image, after our likeness. Let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth.”
> 27 God created man in his own image. In God’s image he created him; male and female he created them.
> 28 God blessed them. God said to them, “Be fruitful, multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth.”
> 29 God said, “Behold, I have given you every herb yielding seed, which is on the surface of all the earth, and every tree, which bears fruit yielding seed. It will be your food.
> 30 To every animal of the earth, and to every bird of the sky, and to everything that creeps on the earth, in which there is life, I have given every green herb for food;” and it was so.
> 31 God saw everything that he had made, and, behold, it was very good. There was evening and there was morning, a sixth day.
> -- Genesis 1:26-31 WEB

===== Ephesians 2 vs 4-6

> 4 But God, being rich in mercy, for his great love with which he loved us,
> 5 even when we were dead through our trespasses, made us alive together with Christ—by grace you have been saved—
> 6 and raised us up with him, and made us to sit with him in the heavenly places in Christ Jesus,
> -- Ephesians 2:4-6 WEB
