== Parenting

=== Love & Logic's Key Principles

---

*Mutual Dignity.*
Love and Logic believes that mutual respect and dignity are critical for teaching children how to treat others. Children learn this by how we treat them, and by how we allow them to treat us. This requires setting limits that allow us to take good care of ourselves and the people around us, including our children.

*Shared Control.*
Power struggles between parents and children are fundamentally about control. When we try to exert control over others, we lose it, but when we share control, we can gain it. Children become happier, more respectful, and stronger when they learn how to handle life’s consequences. They learn this when we allow them to learn how to make responsible decisions through having plenty of small choices and living with the consequences of their choices.

*Shared Thinking.*
Enabling children to think about the consequences of their choices is a lifelong gift. By sharing the thinking process with them, they learn how to think on their own and solve their own problems at an early age.

*Sincere Empathy.*
When we respond to children with anger and frustration, they will respond with defensiveness and defiance. When we respond with empathy, there is a much better chance that we will encourage them to think about their behaviors and consequences. Nothing works without empathy!

*Loving Relationships.*
By following these principles parents will naturally develop a loving and mutually respectful relationship with their children. Kids learn to see their parents as both powerful and loving, and they are much more likely to grow up and become respectful, responsible adults.

Quoted form their Newsletter "Insiders Club" sent on the 25th of January

---

=== Peer Pressure
* If you are always telling your kids what to do they may simply start listening to someone else

=== Bullying

=== Responsibility
* For chores, school etc.

=== lack of Self COnfidence

---
Few things can tear at our hearts more than hearing our kids say, “I’m stupid.” At first glance the following parent seems to be right on track:

No, you are not stupid! Think of all the things you are good at. How about reading? You’re good at that! And remember how much you improved in baseball last summer. Stupid kids don’t learn how to hit curve balls like you did. And your art is wonderful. If you were dumb, would you have been able to learn how to create those drawings with such wonderful three-dimensional perspectives? I don’t think so!

At second glance, we realize that this well-meaning parent is lending credibility to their child’s remark by spending so much time and energy addressing it.

Listed below are other tactics that have created selfish kids rather than ones with a good sense of self:

Constant praise
Ensuring that they are always the center of attention
Making sure that they never encounter any hardships
Buying them everything they want
Rescuing them from the consequences of their misbehavior
Setting no limits so that they can “express their creativity”
Instead of using these tactics, consider employing a much simpler approach, one that avoids unintentionally reinforcing your youngster’s self-deprecating remarks. The most effective parents smile, pat their child on the back, and give this sweet and simple response:

Aren’t you glad I don’t believe that!

For truly improving self-concept, there’s only one approach that really works in the long term, and it’s based on the age-old truism:

The best way to feel good is to do something good.

When parents place a high emphasis on good and respectful behavior, children look at themselves and think, “I act pretty darn good and responsible. I must be pretty darn good and responsible.”

True self-concept is developed when children encounter struggles, are taught how to overcome those struggles, and see themselves acting in respectful and responsible ways. Stated quite simply, self-concept is an inside job.

Shaping Self-Concept, one of our most popular audios, teaches a very special type of love. It’s the type that allows our kids to struggle, lets them work through their trials, and guides them toward independence instead of insecurity.

https://www.loveandlogic.com/products/shaping-self-concept?utm_source=Kajabi&utm_medium=Weekly+Insider+Club&utm_campaign=Shaping+Self+Concept+-+Bullying&utm_term=Shaping+Self+Concept&utm_content=Audio

Self-concept is also important for empowering your kids to handle teasing and bullying, which is the topic we'll be sharing tips about in next week's free virtual event, When Your Child Is Teased or Bullied.

Love & Logic Newsletter 2024.01.04
---
