== Parenting

=== Love & Logic's Key Principles

---

*Mutual Dignity.*
Love and Logic believes that mutual respect and dignity are critical for teaching children how to treat others. Children learn this by how we treat them, and by how we allow them to treat us. This requires setting limits that allow us to take good care of ourselves and the people around us, including our children.

*Shared Control.*
Power struggles between parents and children are fundamentally about control. When we try to exert control over others, we lose it, but when we share control, we can gain it. Children become happier, more respectful, and stronger when they learn how to handle life’s consequences. They learn this when we allow them to learn how to make responsible decisions through having plenty of small choices and living with the consequences of their choices.

*Shared Thinking.*
Enabling children to think about the consequences of their choices is a lifelong gift. By sharing the thinking process with them, they learn how to think on their own and solve their own problems at an early age.

*Sincere Empathy.*
When we respond to children with anger and frustration, they will respond with defensiveness and defiance. When we respond with empathy, there is a much better chance that we will encourage them to think about their behaviors and consequences. Nothing works without empathy!

*Loving Relationships.*
By following these principles parents will naturally develop a loving and mutually respectful relationship with their children. Kids learn to see their parents as both powerful and loving, and they are much more likely to grow up and become respectful, responsible adults.

Quoted form their Newsletter "Insiders Club" sent on the 25th of January

---

=== Peer Pressure
* If you are always telling your kids what to do they may simply start listening to someone else

=== Bullying

=== Responsibility
* For chores, school etc.
