=== Justice, Mercy & Redemption

How do we build a kingdom society that is just, but restores the “unjust”
Introduction


> …But you go and learn what this means: ‘I desire mercy, and not sacrifice,’✡ for I came not to call the righteous, but sinners to repentance.”
> -- Matthew 9:13 WEB


Justice is always an emotional topic in every society. Having to face a mother or father who has lost their child due to a sick murder or something similar must be one of the hardest jobs for a judge. The question that goes through their mind often is, “How do I ensure justice is served and that people will be dissuaded from this crime whilst still seeing the perpetrator through the eyes of Jesus seeking to find a way where this person could be redeemed?”

Grace & truth needs to be at the heart of our justice system. The truth needs to be told and nothing remain unhidden; however, we need a process whereby people can be redeemed and rebuild trust with society whereby they can be integrated back into society.

