=== Finances

==== Introduction
* In the kingdom our view of money is different

==== From a kingdom perspective

==== Money is like seed
* The parable of the farmer
** A farmer plants crops and yields a harvest at harvest time
** When a farmer takes a seed an plants it, it usually grows and produces more seed 10,100,100 fold
** At harvest time he usually makes a decision to keep some of the seed to eat or sell
*** But if he is wise he will keep a substantial portion of the seed to plant in the next planting season
*** If he does not do this he will eventually starve and go bankrupt
** Money should be handled in a similar fashion
*** We work and accordingly earn money
*** However, we should invest a good portion of the money we earn to ensure we can grow a yield for the future
**** where we may no loinger be able to work
**** or to invest in kingdom initiatives e.g. family's education, missions, new businesses, healthcare in old age etc.
*** If we are good stewards and invest we may even be able to free up our time, live off our investments and give our time fully to the Lord

==== Good Stewards
* Stewarding your money well prepares you to be rewarded with spiritual gifts that the Lord gives you to steward
