==== Healing, Health & Wholeness
> 5 But he was pierced (wounded) for our transgressions. He was crushed (bruised) for our iniquities. The punishment that brought our peace was on him; and by his wounds (stripes) we are healed.
> -- Isaiah 53:5 WEB

> 24 He himself bore our sins in his (own) body on the tree, that we, having died to sins, might live to (for) righteousness. You were healed by his wounds (--by whose stripes you were healed).
> -- 1 Peter 2:24 WEB



> -- Romans 8:11 WEB

> 7 For God didn’t give us a spirit of fear, but of power, love, and self-control (sound mind).
> -- 2 Timothy 1:7 WEB

> 63  It is the spirit who gives life. The flesh profits nothing. The words that I speak to you are spirit, and are life.
> -- John 6:63

> 26 He said, “If you will diligently listen to Yahweh your God’s voice, and will do that which is right in his eyes, and will pay attention to his commandments, and keep all his statutes, I will put none of the diseases on you which I have put on the Egyptians; for I am Yahweh who heals you.”
> -- Exodus 15:26

> 1 Blessed is he who considers the poor. Yahweh will deliver him in the day of evil.
>
> 2 Yahweh will preserve him, and keep him alive. He shall be blessed on the earth, and he will not surrender him to the will of his enemies.
>
> 3 Yahweh will sustain him on his sickbed, and restore him from his bed of illness.
> -- Psalm 41:1-3 WEB


> By David.
>
> 1 Praise Yahweh, my soul! All that is within me, praise his holy name!
>
> 2 Praise Yahweh, my soul, and don’t forget all his benefits,
>
> 3 who forgives all your sins, who heals all your diseases,
>
> 4 who redeems your life from destruction, who crowns you with loving kindness and tender mercies,
>
> 5 who satisfies your desire with good things, so that your youth is renewed like the eagle’s.
>
> 6 Yahweh executes righteous acts, and justice for all who are oppressed.
>
> 7 He made known his ways to Moses, his deeds to the children of Israel.
>
> 8 Yahweh is merciful and gracious, slow to anger, and abundant in loving kindness.
>
> 9 He will not always accuse; neither will he stay angry forever.
>
> 10 He has not dealt with us according to our sins, nor repaid us for our iniquities.
>
> 11 For as the heavens are high above the earth, so great is his loving kindness toward those who fear him.
>
> 12 As far as the east is from the west, so far has he removed our transgressions from us.
>
> 13 Like a father has compassion on his children, so Yahweh has compassion on those who fear him.
>
> 14 For he knows how we are made. He remembers that we are dust.
>
> 15 As for man, his days are like grass. As a flower of the field, so he flourishes.
>
> 16 For the wind passes over it, and it is gone. Its place remembers it no more.
>
> 17 But Yahweh’s loving kindness is from everlasting to everlasting with those who fear him, his righteousness to children’s children,
>
> 18 to those who keep his covenant, to those who remember to obey his precepts.
>
> 19 Yahweh has established his throne in the heavens. His kingdom rules over all.
>
> 20 Praise Yahweh, you angels of his, who are mighty in strength, who fulfill his word, obeying the voice of his word.
>
> 21 Praise Yahweh, all you armies of his, you servants of his, who do his pleasure.
>
> 22 Praise Yahweh, all you works of his, in all places of his dominion. Praise Yahweh, my soul!
>
> -- Psalm 103 WEB
